# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md

required = [
  "github.com/fabric8-services/fabric8-common/goasupport/jsonapi_errors_helpers", # needed by goa generator
  "github.com/fabric8-services/fabric8-common/goasupport/status", # needed by goa generator
  "github.com/fabric8-services/fabric8-common/errors", # needed by goa generator
  "github.com/goadesign/goa/cors",
  "github.com/goadesign/goa/encoding/form",
  "github.com/goadesign/goa/goagen",
  "github.com/goadesign/goa/goagen/codegen",
  "github.com/goadesign/goa/goagen/gen_app",
  "github.com/goadesign/goa/goagen/gen_controller",
  "github.com/goadesign/goa/goagen/gen_swagger",
  "github.com/goadesign/goa/goagen/gen_client",
  "github.com/goadesign/goa/goagen/gen_js",
  "github.com/goadesign/goa/goagen/utils",
  "github.com/goadesign/goa/goatest",
  "github.com/davecgh/go-spew/spew",
  "github.com/golang/lint/golint",
  "github.com/jteeuwen/go-bindata/go-bindata",
  "github.com/fzipp/gocyclo",
  "github.com/pilu/fresh", # used to rebuild if source changed while running
  "github.com/wadey/gocovmerge",
]

ignored = [
  "github.com/fabric8-services/fabric8-env/app",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/jteeuwen/go-bindata"
  revision = "v3.0.7"

[[constraint]]
  name = "github.com/fabric8-services/fabric8-common"
  revision = "45960af9689499e9f5e5a4ebd142a8189a19ca1e"
